name=libwally-core
version=1.5.6
author=ElementsProject
maintainer=ElementsProject
sentence=Cross-platform wallet primitives for Bitcoin and Liquid.
paragraph=Bowser-vendored embedded build of libwally-core with Bitcoin-only ABI.
category=Data Processing
url=https://github.com/ElementsProject/libwally-core
architectures=esp32
includes=libwally.h

